name: SCA - Complete Security Pipeline

on:
  pull_request:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sca:
    name: Software Composition Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # Trivy - Dependency Scan (Filesystem) - working

      - name: Trivy SCA - Dependencies (FS Scan)
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: json
          output: trivy-dependencies.json
          exit-code: 0 # don't stop the code

      # Build docker images
      - name: Build backend image
        run: docker build -t isctespot-backend ./server
      - name: Build frontend image
        run: docker build -t isctespot-frontend ./frontend/admin-one-vue-tailwind-master

      # Trivy - Docker Image Scan

      # Scan backend image
      - name: Trivy scan backend image
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: isctespot-backend
          format: json
          output: trivy-backend.json
          exit-code: 0

      # Scan frontend image
      - name: Trivy scan frontend image
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: isctespot-frontend
          format: json
          output: trivy-frontend.json
          exit-code: 0

      # OWASP Dependency-Check 

      - name: OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "IscteSpot"
          path: "."
          format: "HTML"
          out: dependency-check.html #output is not recognized by dep-check
 
      # SBOM - Dependency inventory (Security context)

      - name: Generate SBOM (CycloneDX)
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: cyclonedx-json
          output-file: sbom.json

      # Upload SCA artifacts 

      - name: Upload SCA artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sca-security-artifacts
          path: |
            trivy-dependencies.json
            trivy-frontend.json
            trivy-backend.json
            dependency-check.html
            sbom.json

      - name: Upload findings to DefectDojo
        run: |
          pip install defectdojo-api
          python scripts/upload_defectdojo.py
        env:
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
          DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
          DEFECTDOJO_ENGAGEMENT_ID: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}
